### ISSUE TITLE
Should Multiplier of 1 be close to the actual amount needed to replace water lost due to evapotranspiration?

### ISSUE THREAD

**Issue by dlindnegm** [jeroenterheerdt/HAsmartirrigation#186]
### What happened?

A question on the run time values I'm seeing:

6 sq ft 1.4705 gpm
PyETO w/ no forecast Using my sensors
Multiplier 1 = 906 seconds run time (15 min) (22 gal)
Multiplier .08 = 71 seconds

I know from experience that the daily water for that zone shouldn't need to be over 60 seconds, so I've needed to reduce the multiplier from 1.0 to 0.08 in order to bring the run time into a reasonable range. Is it normal to need to use such a small multiplier value? 22 gallons would be enough to water that area for a full month, way more than needed to replace a single days evapotranspiration! I would have thought that the results would at least be in the ball park and not need such a large adjustment. This zone consists of several hanging potted plants so I know to reduce the multiplier, but how would I know how much to reduce it for a larger zone such as a several thousand square foot grass yard?

Another example:
Lawn area of 2400 sq ft with a flow rate of 2.7149 gpm and a multiplier of 1 generates a run time of 201554 seconds.  That's almost 60 hours of irrigation and 9,119 gallons of water per day!

### How to reproduce

Name: Rear Yard
Size (sq ft): 2400
Throughput (gal/minute): 2.7149
State: Automatic
 Module: 0: PyETO
 Mapping: 1: My Sensors
Bucket: -3.8
 Lead time (s): 0
Multiplier: 1
 Duration (s): 201554

Using OWM instead of my sensors produces a longer run time of 259899 seconds or 11,759 gallons.

[config_entry-smart_irrigation-b243bc1b533c4e97f3a27859a84bd373.json (3).txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12422619/config_entry-smart_irrigation-b243bc1b533c4e97f3a27859a84bd373.json.3.txt)

### Which version are you running?

beta 22

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by dlindnegm** [comment]
Trying to check the math used.  Even if it's off it seems way too high.

Module returned Evapotranspiration deficiency of -4.9. Bucket was 0.0.
New bucket value is [old_bucket]+[delta]=0.0+-4.9=-4.9.
Since bucket < 0, irrigation is necessary.
To calculate the exact duration, the following steps were taken:
The precipitation rate is defined as[throughput]*60/[size]=2.7149*60/2400.0=0.1
The duration is calculated as abs([bucket])/[precipitation_rate]*3600=4.9/0.1*3600=259899
Now, the multiplier is applied. The multiplier is 1.0, hence the duration is 259899
Finally, the lead time is applied. The lead time is 0.0, hence the final duration is 259899

Duration:
abs([bucket])/[precipitation_rate]*3600
=4.9/0.1*3600=259899

By my calculation:
4.9/0.1*3600=176400

**Comment by jeroenterheerdt** [comment]
yeah, this is a problem. Not sure where the issue is. What we could do is record the numbers and then call the FAO56 calc from PyETO with those. I think that in my redo in V2 I missed a or multiple unit conversions. We can set up a test class to get to the bottom of this, but I agree, this is way too high.

**Comment by dlindnegm** [comment]
I created a bunch of zones with incrementing sq ft areas and found that the math as reported starts to fail for anything above 1000 sq ft.  There may also be a division by zero issue once the precip is 0.0.

100 sq ft:
1.669*60/100.0=1.0	
3.8/1.0*3600=13661	OK

500 sq ft:
1.669*60/500.0=0.2	
3.8/0.2*3600=68304	OK

1000 sq ft:
1.669*60/1000.0=0.1	
3.8/0.1*3600=136609	OK

1001 sq ft:
1.669*60/1001.0=0.1
3.7/0.1*3600=133147	OK

1010 sq ft:
1.669*60/1010.0=0.1
3.8/0.1*3600=137975	Should be 136800

1020 sq ft:
1.669*60/1020.0=0.1
3.8/0.1*3600=139341	Should be 136800

1100 sq ft:
1.669*60/1100.0=0.1
3.8/0.1*3600=150270	Should be 136800

1200 sq ft:
1.669*60/1200.0=0.1	
3.8/0.1*3600=163930	Should be 136800

1500 sq ft:
1.669*60/1500.0=0.1
3.8/0.1*3600=204913	Should be 136800

1800 sq ft:
1.669*60/1800.0=0.1
3.8/0.1*3600=245896	Should be 136800

2000 sq ft:
1.669*60/2000.0=0.1
3.8/0.1*3600=273217	Should be 136800

5000 sq ft:
1.669*60/5000.0=0.0
3.8/0.0*3600=683044	Division by zero???

10000 sq ft:
1.669*60/10000.0=0.0
3.8/0.0*3600=1366087	Division by zero???

**Comment by jeroenterheerdt** [comment]
I found a big fat bug!
when calculating the precipitation rate there is no conversion from gpm to lpm and from sq ft to m2, which should be done because OWM returns metric values. Also, note that your sensor values are converted to metric internally as well so the bug is the same for this, so I am guessing we will end up with a higher number of when you run with your sensors on.

I did some calcs and it is still way high, but in the ballpark of 2 hours now for a bucket of -6, which was what I got when I ran it now and not 60 hours. 

Stay tuned for the fixed version, hoping it now gets closer to your sensor values. OWM will almost always be higher and sometimes significantly so just because it's less tailored.

**Comment by jeroenterheerdt** [comment]
https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2023.8.0-beta23 👀

**Comment by dlindnegm** [comment]
Much more realistic numbers now!  But the math is still off.  It gets exaggerate as the sq footage increases, but some of those are higher than the math indicates while some are lower.

100 sq ft:
3.8/66.4*3600=206 Should be 207 Diff = -1

500 sq ft:
3.8/13.3*3600=1031 Should be 1028 Diff = -3

1000  sq ft"
3.8/6.6*3600=2061 Should be 2,072 Diff = -11

2400 sq ft:
3.8/2.8*3600=4947 Should be 4,885 Diff = +62

5000 sq ft:
3.8/1.3*3600=10305 Should be 10,523 Diff = -218

10000 sq ft:
3.8/0.7*3600=20611 Should be 19,542 Diff = +1,069

**Comment by jeroenterheerdt** [comment]
You are assuming the delta calculated based on the OWM data is the same as your sensor, which it's likely not. So we should really check the numbers returned by OWM. The code for calcuting duration based on weather data is the same regardless of the source used. The issue is likely in the diff between OWM and your sensors so the best way is to try and run this side by side for a couple of days and record the numbers.

**Comment by dlindnegm** [comment]
I understand there's going to be a difference when OWM vs local sensors are used.  But this is about the basic math being performed as shown in the Information dialog after any calculation.  I'm not using OWM at all - just my own sensors.  But, the math doesn't add up even when using only OWM sensors.  

To reproduce:

1) Create a zone with a square footage of 10,000 feet.
2) Set a flow rate of 0.521 gpm.
3) Update and Calculate the zone.
4) View the Information for the zone.

The duration is calculated as abs([bucket])/[precipitation_rate]*3600=2.4/0.1*3600=**_67833_**
The math shown above is incorrect: 2.4/0.1*3600=**_86400_**
That's a difference of of 18567 seconds or 5 hours.

This happens for any square footage, but for numbers under 1000 sq ft I figured it was just a rounding error.  But as you approach 1000 and above the difference gets worse regardless of using OWM or local sensors.

Diag file attached
[config_entry-smart_irrigation-b243bc1b533c4e97f3a27859a84bd373.json (5).txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12430197/config_entry-smart_irrigation-b243bc1b533c4e97f3a27859a84bd373.json.5.txt)

**Comment by jeroenterheerdt** [comment]
Oh, sorry, I haven't been paying too much attention to that part then. Is the duration correct in the end or does that suffer the same issue? The way this works is that I calculate everything and show it rounded in the UI (to one or zero decimals) to make it easier to read. So maybe it's really just a rounding error... I can stop rounding for a sec and see if that makes a difference.

**Comment by jeroenterheerdt** [comment]
Yeah, I think it 's result of compounded rounding somewhere. I am going to remove all rounding for a while to see if it goes away... Peeling the onion

**Comment by jeroenterheerdt** [comment]
ok, I removed all roundings temporarily in beta 25 (https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2023.8.0-beta25). Please check if this helps, @dlindnegm. I am unable to spot a major difference right away on my side.

**Comment by dlindnegm** [comment]
The math proves accurate in beta 25 up to 10000 sq ft:

The duration is calculated as abs([bucket])/[precipitation_rate]*3600=0.22492077564429452/0.6465385833131341*3600=1252.3843328423543

Is the plan to remove the rounding for the calculation and only apply it to the final duration?  
i.e. 1252.3843328423543 rounds to 1252

I'm still seeing a huge difference between using OWM sensors and my own though:
Using my sensors:
Evapotranspiration deficiency of -0.6710211958681421

Using OWM sensors:
Evapotranspiration deficiency of -4.029286758035393

That results in a run time difference of 4503 seconds (75 minutes/198 gallons).  I know there will always be a difference, but which one do I trust and why are they so far off?

**Comment by jeroenterheerdt** [comment]
so @dlindnegm in 2023.9.0-beta2 I have made major changes that treat OWM as sensor values. Assuming it all works fine (which I am not sure of) the difference between using your own sensors and OWMs data should be less big. Can you install that version and try please?

**Comment by dlindnegm** [comment]
Unable to install v2023.9.0-beta3 - I'll try beta2 next.
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/smart_irrigation/store.py:192
Integration: Smart Irrigation (documentation, issues)
First occurred: 10:43:43 PM (1 occurrences)
Last logged: 10:43:43 PM

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 62, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 527, in async_get_registry
    return cast(SmartIrrigationStorage, await task)
                                        ^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 522, in _load_reg
    await registry.async_load()
  File "/config/custom_components/smart_irrigation/store.py", line 192, in async_load
    maximum_duration = zone[ZONE_MAXIMUM_DURATION]
                       ~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'maximum_duration'

**Comment by jeroenterheerdt** [comment]
Uninstall and reinstall can help, but I need to fix this as well. Not sure how exactly though.

**Comment by dlindnegm** [comment]
I was on beta25, which was working.  I then installed v2023.9.0-beta3, which failed to install.  Completely removed it, then tried to install v2023.9.0-beta2 - same issue.  Same for v2023.9.0-beta1.  So I then tried to go back to v2023.8.0-beta29,a and it also fails.  Same for v2023.8.0-beta28.  It looks like you've removed beta 25, so I can't go back to that & now I have no working version at all.  If I disable "Show beta versions", it doesn't even show the non-beta versions any more. There is a version labeled "Master", but I'm assuming that's the 1.0 version.   All of these fail immediately after entering the OWM API key, which is accepted with a success message.

**Comment by jeroenterheerdt** [comment]
it's weird, I can install beta versions fine, do uninstalls, switch to other versions... anyway, I found the bug that stopped you from installing beta3, so hopefully beta4 works?

**Comment by dlindnegm** [comment]
No joy.
I've completely removed everything and confirmed that the custom_components folder is removed and restarted.  Now when I try to install from HACS there is no prompt for selecting any version at all, and no option for selecting any beta version.  It does download version   0.0.81.  Seems like something is messed up with the repository.

**Comment by jeroenterheerdt** [comment]
Weird. I tried it on my production install again and am able to install any beta version just fine. I seriously have no idea. Did you try to update info in HACS?

**Comment by dlindnegm** [comment]
Seems like something hammered my HACS during one of the updates.  I have a VM with a test HA installed and it sees all the versions.  Reinstalling HACS now......

**Comment by jeroenterheerdt** [comment]
Ugh, no idea what happened there then

**Comment by jeroenterheerdt** [comment]
> Seems like something hammered my HACS during one of the updates. I have a VM with a test HA installed and it sees all the versions. Reinstalling HACS now......

Did that do the trick?

**Comment by dlindnegm** [comment]
Is there a trick to being able to see the beta versions?  I thought there should be an option in the menu, but that's what I'm missing.  v0.0.81 is all I can install even after multiple attempts.  I suppose I can download the beta code directly and manually install it, but I'm not sure I'll ever get notified if there's a future update available.

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/24968305/c3fed278-5b5d-4bfb-b5ab-c8a0dcb74799)

**Comment by jeroenterheerdt** [comment]
> Is there a trick to being able to see the beta versions? I thought there should be an option in the menu, but that's what I'm missing. v0.0.81 is all I can install even after multiple attempts. I suppose I can download the beta code directly and manually install it, but I'm not sure I'll ever get notified if there's a future update available.
> 
> ![image](https://user-images.githubusercontent.com/24968305/265227502-c3fed278-5b5d-4bfb-b5ab-c8a0dcb74799.png)

What I do is update information and then re-download. That gives me the beta versions to download. Does that help?

**Comment by gatonero** [comment]
That doesn't work for me also. I opened an issue in the HACS repository [No option 'Show beta versions' when downloading an extension](https://github.com/hacs/integration/issues/3242)

**Comment by dlindnegm** [comment]
That seems to have worked - performing the update information & then downloading.  I now have v2023.9.0-beta6 installed, but it doesn't seem to work.  I configured it with my 3.0 API key & haven't changed anything else.  So I have the default sensor group with all defaults selected (All OWM sensors & no Evapotranspiration sensor).  The default PyETO module is untouched, and I left the 2 default zones untouched.  Just clicking on Update all Zones generates the error below.  Diag files are attached.  Should I not be able to update and calculate with just the default sensor group and zones?

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/smart_irrigation/__init__.py:328
Integration: Smart Irrigation (documentation, issues)
First occurred: 6:46:03 PM (1 occurrences)
Last logged: 6:46:03 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/websockets.py", line 176, in post
    await coordinator.async_update_zone_config(zone, data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 757, in async_update_zone_config
    await self._async_update_all()
  File "/config/custom_components/smart_irrigation/__init__.py", line 328, in _async_update_all
    mapping_data = mapping[const.MAPPING_DATA]
                   ^^^^^^^
UnboundLocalError: cannot access local variable 'mapping' where it is not associated with a value


[home-assistant_smart_irrigation_2023-09-02T22-48-34.434Z.log](https://github.com/jeroenterheerdt/HAsmartirrig
[config_entry-smart_irrigation-917d7ff709c6d43e70ce27febe8b3918.json (1).txt]

(https://github.com/jeroenterheerdt/HAsmartirrigation/files/12504850/config_entry-smart_irrigation-917d7ff709c6d43e70ce27febe8b3918.json.1.txt)
ation/files/12504849/home-assistant_smart_irrigation_2023-09-02T22-48-34.434Z.log)

**Comment by jeroenterheerdt** [comment]
> That seems to have worked - performing the update information & then downloading. I now have v2023.9.0-beta6 installed, but it doesn't seem to work. I configured it with my 3.0 API key & haven't changed anything else. So I have the default sensor group with all defaults selected (All OWM sensors & no Evapotranspiration sensor). The default PyETO module is untouched, and I left the 2 default zones untouched. Just clicking on Update all Zones generates the error below. Diag files are attached. Should I not be able to update and calculate with just the default sensor group and zones?
> 
> This error originated from a custom integration.
> 
> Logger: aiohttp.server Source: custom_components/smart_irrigation/**init**.py:328 Integration: Smart Irrigation (documentation, issues) First occurred: 6:46:03 PM (1 occurrences) Last logged: 6:46:03 PM
> 
> Error handling request Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request resp = await request_handler(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle resp = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle result = await handler(request, **request.match_info) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper result = await method(view, request, data, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smart_irrigation/websockets.py", line 176, in post await coordinator.async_update_zone_config(zone, data) File "/config/custom_components/smart_irrigation/**init**.py", line 757, in async_update_zone_config await self._async_update_all() File "/config/custom_components/smart_irrigation/**init**.py", line 328, in _async_update_all mapping_data = mapping[const.MAPPING_DATA] ^^^^^^^ UnboundLocalError: cannot access local variable 'mapping' where it is not associated with a value
> 
> [home-assistant_smart_irrigation_2023-09-02T22-48-34.434Z.log](https://github.com/jeroenterheerdt/HAsmartirrig [config_entry-smart_irrigation-917d7ff709c6d43e70ce27febe8b3918.json (1).txt]
> 
> (https://github.com/jeroenterheerdt/HAsmartirrigation/files/12504850/config_entry-smart_irrigation-917d7ff709c6d43e70ce27febe8b3918.json.1.txt) ation/files/12504849/home-assistant_smart_irrigation_2023-09-02T22-48-34.434Z.log)

thanks for letting me know you were able to install the betas now! @gatonero have you tried this same approach as well?
Now regarding the bug reported by @dlindnegm in the quoted message, I have fixed that one in beta7. I apparently forgot to update the code for update_all and only did it for update (one). Oops. Beta7 should help!

**Comment by dlindnegm** [comment]
Beta 7 no longer generates any errors when performing an update, either for an individual zone or for all zones.  But now the calculate fails with the error below, also for either an individual or calculate all.

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/smart_irrigation/__init__.py:375
Integration: Smart Irrigation (documentation, issues)
First occurred: 8:58:25 AM (2 occurrences)
Last logged: 8:58:32 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/statistics.py", line 327, in _exact_ratio
    return (x.numerator, x.denominator)
            ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'numerator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/websockets.py", line 176, in post
    await coordinator.async_update_zone_config(zone, data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 691, in async_update_zone_config
    sensor_values = await self.apply_aggregates_to_mapping_data(mapping)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 375, in apply_aggregates_to_mapping_data
    resultdata[key] = statistics.mean(d)
                      ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/statistics.py", line 430, in mean
    T, total, n = _sum(data)
                  ^^^^^^^^^^
  File "/usr/local/lib/python3.11/statistics.py", line 193, in _sum
    for n, d in map(_exact_ratio, values):
  File "/usr/local/lib/python3.11/statistics.py", line 330, in _exact_ratio
    raise TypeError(msg)
TypeError: can't convert type 'list' to numerator/denominator

[config_entry-smart_irrigation-917d7ff709c6d43e70ce27febe8b3918.json (2).txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12506085/config_entry-smart_irrigation-917d7ff709c6d43e70ce27febe8b3918.json.2.txt)


[config_entry-smart_irrigation-917d7ff709c6d43e70ce27febe8b3918.json (2).txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12506086/config_entry-smart_irrigation-917d7ff709c6d43e70ce27febe8b3918.json.2.txt)

**Comment by jeroenterheerdt** [comment]
> Beta 7 no longer generates any errors when performing an update, either for an individual zone or for all zones. But now the calculate fails with the error below, also for either an individual or calculate all.
> 
> This error originated from a custom integration.
> 
> Logger: aiohttp.server Source: custom_components/smart_irrigation/**init**.py:375 Integration: Smart Irrigation (documentation, issues) First occurred: 8:58:25 AM (2 occurrences) Last logged: 8:58:32 AM
> 
> Error handling request Traceback (most recent call last): File "/usr/local/lib/python3.11/statistics.py", line 327, in _exact_ratio return (x.numerator, x.denominator) ^^^^^^^^^^^ AttributeError: 'list' object has no attribute 'numerator'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request resp = await request_handler(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle resp = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle result = await handler(request, **request.match_info) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper result = await method(view, request, data, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smart_irrigation/websockets.py", line 176, in post await coordinator.async_update_zone_config(zone, data) File "/config/custom_components/smart_irrigation/**init**.py", line 691, in async_update_zone_config sensor_values = await self.apply_aggregates_to_mapping_data(mapping) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smart_irrigation/**init**.py", line 375, in apply_aggregates_to_mapping_data resultdata[key] = statistics.mean(d) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/statistics.py", line 430, in mean T, total, n = _sum(data) ^^^^^^^^^^ File "/usr/local/lib/python3.11/statistics.py", line 193, in _sum for n, d in map(_exact_ratio, values): File "/usr/local/lib/python3.11/statistics.py", line 330, in _exact_ratio raise TypeError(msg) TypeError: can't convert type 'list' to numerator/denominator
> 
> [config_entry-smart_irrigation-917d7ff709c6d43e70ce27febe8b3918.json (2).txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12506085/config_entry-smart_irrigation-917d7ff709c6d43e70ce27febe8b3918.json.2.txt)
> 
> [home-assistant_smart_irrigation_2023-09-03T13-05-15.551Z.log](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12506094/home-assistant_smart_irrigation_2023-09-03T13-05-15.551Z.log)

That's weird. I have never seen this before. It works fine on my end but of course my config is different than yours. Will take a look!

**Comment by jeroenterheerdt** [comment]
This was fixed in beta 8, please try it.

**Comment by dlindnegm** [comment]
Update and calculate are working now with beta 8 with initial defaults.  Let me add my sensors and continue testing...

**Comment by dlindnegm** [comment]
No errors, but it looks like the rounding issue is still not resolved:
- Set any zone to 10,000 sq ft
- Set Max Duration to 100000
- Calculation should be 3.7/0.6*3600=22200, not 20361, for a difference of 1839 sec or 30+ minutes.

Module returned Evapotranspiration deficiency of -3.7. Bucket was 0.
maximum bucket size is 50.0.New bucket value is [old_bucket]+[delta]=0+-3.7=-3.7.
Since bucket < 0, irrigation is necessary.
To calculate the exact duration, the following steps were taken:
The precipitation rate is defined as [throughput]*60/[size]=2.6446*60/10000.0=0.6
The duration is calculated as abs([bucket])/[precipitation_rate]*3600=3.7/0.6*3600=20361 
Now, the multiplier is applied. The multiplier is 1.0, hence the duration is 20361
Then, the maximum duration is applied. The maximum duration is 100000.0,
Finally, the lead time is applied. The lead time is 0.0, hence the final duration is 20361

**Comment by jeroenterheerdt** [comment]
> No errors, but it looks like the rounding issue is still not resolved:
> 
> * Set any zone to 10,000 sq ft
> * Set Max Duration to 100000
> * Calculation should be 3.7/0.6*3600=22200, not 20361, for a difference of 1839 sec or 30+ minutes.
> 
> Module returned Evapotranspiration deficiency of -3.7. Bucket was 0. maximum bucket size is 50.0.New bucket value is [old_bucket]+[delta]=0+-3.7=-3.7. Since bucket < 0, irrigation is necessary. To calculate the exact duration, the following steps were taken: The precipitation rate is defined as [throughput]_60/[size]=2.6446_60/10000.0=0.6 The duration is calculated as abs([bucket])/[precipitation_rate]_3600=3.7/0.6_3600=20361 Now, the multiplier is applied. The multiplier is 1.0, hence the duration is 20361 Then, the maximum duration is applied. The maximum duration is 100000.0, Finally, the lead time is applied. The lead time is 0.0, hence the final duration is 20361

Well... No. We use unrounded values to calculate the 20361 in your example. The explanation just shows rounded values to make it easier to read. I'd say the 20361 is correct because it's based on unrounded values. Not sure what you prefer?

Just to remind ourselves, we still need to figure out if OWM is now closer to expected values (that's what started this thread).

**Comment by dlindnegm** [comment]
No new issues so far, but I'm still seeing a big difference between using OWM vs my sensors for the bucket sizes (OWM=-0.7 and my sensors=-3.7).  I've narrowed it down to when I use the  min and max from the Daily Sensor, and it doesn't matter if I select the option for minimum, maximum, or last.  I tried using just a current outdoor temp sensor, and that closely matches the results from using the OWM sensors, but I'm assuming that you can't actually calculate the min and max from an outdoor sensor, so no matter which option I select it's just using the current, or last value from that sensor?  Is there anything in the logs or an OWM API I can call to see what they are reporting for my areas min and max and compare that to my physical sensors?

**Comment by dlindnegm** [comment]
I'm OK with the rounding method - it's just confusing if anyone tries to use a calculator to verify the math!  And it only starts becoming apparent when you go above 1000 sq ft.

**Comment by jeroenterheerdt** [comment]
> I'm OK with the rounding method - it's just confusing if anyone tries to use a calculator to verify the math! And it only starts becoming apparent when you go above 1000 sq ft.

that's why the first line of the explanation says: 'this uses rounded values'

**Comment by jeroenterheerdt** [comment]
> No new issues so far, but I'm still seeing a big difference between using OWM vs my sensors for the bucket sizes (OWM=-0.7 and my sensors=-3.7). I've narrowed it down to when I use the min and max from the Daily Sensor, and it doesn't matter if I select the option for minimum, maximum, or last. I tried using just a current outdoor temp sensor, and that closely matches the results from using the OWM sensors, but I'm assuming that you can't actually calculate the min and max from an outdoor sensor, so no matter which option I select it's just using the current, or last value from that sensor? Is there anything in the logs or an OWM API I can call to see what they are reporting for my areas min and max and compare that to my physical sensors?

what you can do (what I do) is: add two zones that are the same in size / throughput. Wire one up to OWM and one to your sensors. OWM uses the following aggregations: all average, except for: min temperature --> min, max temperature --> max, precipitation --> last. You can't set that in the UI, but that's what it does in the code.
So when you set up your sensor group for sensors, make the same aggregate selections.
Set both zones to use a PyETO module with forecast off.
Now, update both zones, once or multiple times over a longer period (or use auto update). Don't enable auto calculate for now.
Open the storage file and scroll down to your sensor groups. The unaggregated, collected weatherdata is shown for each sensor group. You can compare OWM and sensor values that way. Note that all values in the storage file are in metric (OWM provides metric, but in your case (and mine) the values are stored after they are converted to metric). The values in the storage files don't match necessary what you see in your sensors, but you can do the reverse math (and maybe spot bugs that way?)

From there, the code treats these the same (assuming you set up the aggregations for sensors as outlined above). So if you would "calculate" manually these are the steps:
- for each sensor group, apply aggregates (take averages, min, max, last).
- you should now have one value per "data point" per sensor group (dewpoint/max temperature/precipitation)
- compare the values between sensor groups. does anything weird jump out to you? If there is anything weird here, changes are these is an error in the conversion from imperial to metric. Ideally these values should be in the same ballpark. Any big differences here will cause differences down the line.
- since the module is the same for both sensor groups, the functions that get called to calculate duration are the same. So really, the difference can only be caused by two things: 1) difference in data collected from OWM/sensors 2) conversion errors when converting to metric (applies only to sensors that have non-metric units).

Curious to hear what you find!

**Comment by dlindnegm** [comment]
In file smart_irrigation.storage ?  I set up zones Test 1 and Test 2 and performed an update, and I see those 2 zones referenced in the file, but no mention of any weather data.  File is atatched.

[smart_irrigation.storage.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12508774/smart_irrigation.storage.txt)

**Comment by dlindnegm** [comment]
Never mind -  I see it now...

**Comment by dlindnegm** [comment]
What stands out is that OWM has the same value for min, max and current!

My Sensors

          {
            "Dewpoint": 20.055555555555554,      68.099999999999965894 Fahrenheit
            "Humidity": 84.0,
            "Maximum Temperature": 31.277777777777775,      88.299999999999968736 Fahrenheit
            "Minimum Temperature": 17.61111111111111,      63.699999999999938893 Fahrenheit
            "Precipitation": 0.0,
            "Pressure": 980.4276328000001,
            "Solar Radiation": 0.0, 
            "Temperature": 23.000000000000004,    73.399999999999991473 Fahrenheit
            "Windspeed": 0.0
          },

OWM           {
            "Windspeed": 0.8003076504297003,
            "Pressure": 1018,
            "Humidity": 80,
            "Temperature": 21.67,      71.006 Fahrenheit
            "Maximum Temperature": 21.67,      71.006 Fahrenheit
            "Minimum Temperature": 21.67,      71.006 Fahrenheit
            "Dewpoint": 18.07,      64.526
            "Precipitation": 0.0
          }

**Comment by jeroenterheerdt** [comment]
> What stands out is that OWM has the same value for min, max and current!
> 
> My Sensors
> 
> ```
>       {
>         "Dewpoint": 20.055555555555554,      68.099999999999965894 Fahrenheit
>         "Humidity": 84.0,
>         "Maximum Temperature": 31.277777777777775,      88.299999999999968736 Fahrenheit
>         "Minimum Temperature": 17.61111111111111,      63.699999999999938893 Fahrenheit
>         "Precipitation": 0.0,
>         "Pressure": 980.4276328000001,
>         "Solar Radiation": 0.0, 
>         "Temperature": 23.000000000000004,    73.399999999999991473 Fahrenheit
>         "Windspeed": 0.0
>       },
> ```
> 
> OWM { "Windspeed": 0.8003076504297003, "Pressure": 1018, "Humidity": 80, "Temperature": 21.67, 71.006 Fahrenheit "Maximum Temperature": 21.67, 71.006 Fahrenheit "Minimum Temperature": 21.67, 71.006 Fahrenheit "Dewpoint": 18.07, 64.526 "Precipitation": 0.0 }

well yes, of course: if you update OWM once, it will get the current temperature, which is then stored as max/min as well. I presume you only updated once. Update all more than once and you should see those change. For a fair comparison you should keep doing this for a day, collecting data every hour or so, but never calculate. after a day you have a nice comparison set that we can look at. Right now it doesn't look terribly different (OWM is always a bit more 'wide' than your sensors)

**Comment by dlindnegm** [comment]
Ok, they do change, but I don't understand the logic.  If the default is to update at 22:55 and calculate at 23:00, then OWM will still show the same values for min, max and current at that point in time.  So what you are saying is that OWM never actually calculates the min or max, but just uses the current temp for all 3, whereas my sensors (using the Daily sensors)  are actually keeping the history of the min & max for the past 24 hours and using that in the bucket calculations.  If OWM does use the actual min & max for the day, how/where are they being stored?  I have the OWM integration installed and I don't see any values for max, and the sensor.openweathermap_forecast_temperature_low is "unknown".  There is a sensor.openweathermap_forecast_temperature, but that looks to be either the current temp, or maybe it's related to sensor.openweathermap_forecast_time which currently says "In 3 hours",

Current OWM           {
            "Windspeed": 0.8003076504297003,
            "Pressure": 1018,
            "Humidity": 80,
            "Temperature": 21.67, 71.006
            "Maximum Temperature": 21.67, 71.006
            "Minimum Temperature": 21.67, 71.006
            "Dewpoint": 18.07, 64.526
            "Precipitation": 0.0
          }

**Comment by jeroenterheerdt** [comment]
The min max are in daily on the OWM api. I don't retrieve them from there though as of now, as I assume retrieving current multiple times during the day and taking the max or min of that is the same as your sensors right? In the end, your max temp of your sensor is the same: collect temps during the day and keep the highest...
Happy to change the logic to retrieve the min / max from daily OWM data though if we want to try that.

**Comment by dlindnegm** [comment]
AHA!  I didn't realize that you were saving the OWM values each time an update was performed. 

Is there a use case for only calculating once at the end of the day, or at any point in the day, and not being concerned with the min and max actually being correct?  Especially since those 2 values seem to have such a large impact on the calculated bucket size.  If so, then leaving it as-is makes sense.  Otherwise always grabbing the OWM min/max at every update sounds like less code and confusion.   Documentation will be key, as someone (like me!) may change it to once per day and not realize the impact.

**Comment by jeroenterheerdt** [comment]
The v1 collected data every hour on purpose. It's also the default in v2. However if you are concerned about using an API too often or whatever you do have the option to collect it once a day or even less (??) but in reality to get good results I'd recommend at least once every hour or as fast as a free API permits.
So let's see if this makes sense, please do some testing for a day or two or so and see if the values stabilize between OWM and your sensors. In not, we have to dig deeper. We have options.

**Comment by dlindnegm** [comment]
No concern about the number of API calls here.  Just a lack of understanding of how it worked in the background.  I'll check the .storage file with hourly updates at the end of tomorrow and see what those average up to.

**Comment by jeroenterheerdt** [comment]
> No concern about the number of API calls here. Just a lack of understanding of how it worked in the background. I'll check the .storage file with hourly updates at the end of tomorrow and see what those average up to.

To be fair, based on your feedback, I changed how it worked in the background!
