### ISSUE TITLE
Can Only add two Zones

### ISSUE THREAD

**Issue by dMopp** [jeroenterheerdt/HAsmartirrigation#447]
### What happened?

When iam trying to add a third zone, the first one gots overwritten

### How to reproduce

Create a third zone
[config_entry-smart_irrigation-01J36EX5QBDX53M0VXRERGTS12.json](https://github.com/user-attachments/files/16329437/config_entry-smart_irrigation-01J36EX5QBDX53M0VXRERGTS12.json)

### Which version are you running?

v2024.7.6

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by dMopp** [comment]
And i can only add one Sensor group.. the otherone just disappearing/get overwritten. :(

**Comment by jeroenterheerdt** [comment]
I just fixed a bug for sensor groups in the latest version. To be sure you are not hitting that can you please refresh your browser cache and try botn scenarios again?

**Comment by dMopp** [comment]
Didnt fix it. But it always starts with sensor group 2. so same error :(

**Comment by jeroenterheerdt** [comment]
what do you mean "starts with sensor group 2"?

**Comment by dMopp** [comment]
![IMG_1847](https://github.com/user-attachments/assets/ffc9d909-5167-4d11-b398-070aabd4a7ab)
Just one group is there (yes, empty sensor, because every Test overwrites my settings :/

**Comment by jeroenterheerdt** [comment]
that's weird and not supposed to happen. thanks for letting me know.

**Comment by jeroenterheerdt** [comment]
can you try v2024.7.7 (beta version)? install and clear your browser cache, please.

**Comment by dMopp** [comment]
This fixed my issue, Can add now more then 2 Zones and Sensors. (where my sensors still start at 2., but this is just a cosmetic issue)

**Comment by jeroenterheerdt** [comment]
Yeah, that's because of the numbering scheme used. No worries for that, it's just an identifier.
