### ISSUE TITLE
Several inputs missing from sensor groups page

### ISSUE THREAD

**Issue by clarejor** [jeroenterheerdt/HAsmartirrigation#627]
### Did you read the docs?

- [x] I read the docs and my question is not answered there.

### What happened?

The sensor page is missing inputs for units, aggregation, and pressure type. The functions to render these inputs are present in the code of view-mappings.ts, but they are only referenced in `renderMappingInputs()`, which is never called.

### How to reproduce

Go to the sensor groups page, add a sensor group, observe there are missing inputs:

<img width="618" height="493" alt="Image" src="https://github.com/user-attachments/assets/e966515f-cf34-4e2e-826c-21b9c1bc313b" />

### Relevant log output

```shell

```

### Which version are you running?

v2025.7.2

### Diagnostics file

- [x] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-01JT1ZKSD0N51CHZQM6V3KZKQM.json](https://github.com/user-attachments/files/21356090/config_entry-smart_irrigation-01JT1ZKSD0N51CHZQM6V3KZKQM.json)

**Comment by jeroenterheerdt** [comment]
should be fixed in v2025.8.0

**Comment by clarejor** [comment]
@jeroenterheerdt  this issue is still present for me in v2025.8.1

**Comment by clarejor** [comment]
disregard, I needed to delete my browser cache
